server: 
  port: 9901  
spring:
  application:
    name:  microservicecloud-config
spring:
  profiles: 
    active: 
    - jyddev
  
---
spring:
  profiles: jyddev
  
  application:
    name: microservicecloud-edge-dev
---
spring:
  profiles: jydprod
  application:
    name: microservicecloud-edge-prod