server:
  port: 9910
 
ss: bbb
eureka:
  instance:
    hostname: eureka9910.com 
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: 
#      defaultZone: http://eureka9911.com:9911/eureka/,http://eureka9912.com:9912/eureka/
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/